.\" Manpage for market_test.
.\" Contact online@adtoox.com to correct errors or typos.
.TH man 8 "06 May 2019" "1.0" "market_test man page"
.SH NAME
market_test.sh \- testing market 
.SH SYNOPSIS
market_test.sh [OPTIONS]
.SH DESCRIPTION
Testing Adtoox Market server as a client.
.SH OPTIONS
     -u <username>
                 Login username (mandatory)
     -p <password>
                 Login passsword (mandatory)
     -o <host>
                 Market server (default localhost)
     -r <port>
                 Market server port number. (default 50304)
     -a <assetid>
                 Asset id. Used to get asset by id.
     -v
                 Verbose
.SH BUGS
No known bugs.
.SH AUTHOR
Tean online (online@adtoox.com)
